# Generated by Django 5.1.1 on 2024-10-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosptialapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup_db',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='signup_db',
            old_name='Username',
            new_name='username',
        ),
    ]
