# Generated by Django 5.1.1 on 2024-10-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosptialapp', '0002_rename_password_signup_db_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('notspecified', 'Notspecified')], default='Notspecified', max_length=25)),
                ('department', models.CharField(max_length=200)),
                ('phn', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
                ('payment', models.CharField(max_length=200)),
            ],
        ),
    ]
