# Generated by Django 5.1.1 on 2024-10-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosptialapp', '0003_booking_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_db',
            name='phn',
        ),
        migrations.AddField(
            model_name='booking_db',
            name='phone',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking_db',
            name='payment',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
