# Generated by Django 5.1.1 on 2024-10-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosptialapp', '0004_remove_booking_db_phn_booking_db_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=25)),
                ('admin_pass', models.CharField(max_length=25)),
            ],
        ),
    ]
