# Generated by Django 5.1.1 on 2024-10-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosptialapp', '0005_admin_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_db',
            name='status',
            field=models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
