# Generated by Django 5.1.1 on 2024-10-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosptialapp', '0006_booking_db_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_db',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
