# Generated by Django 5.1.1 on 2024-11-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosptialapp', '0007_alter_signup_db_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='docs_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=25)),
                ('doc_id', models.CharField(max_length=25)),
                ('doc_file', models.FileField(max_length=25, upload_to='')),
                ('doc_department', models.CharField(max_length=25)),
            ],
        ),
    ]
